
IMAGE = loader.img
BINFILE=ipl.bin

build: $(IMAGE)

default :
	$(MAKE) img

$(BINFILE) : ipl.nas Makefile
	nasm ipl.nas -o $@
	nasm ipl.nas -o ipl.img

img : $(BINFILE) 
	mformat -f 1440 -C -B $(BINFILE)  -i helloos.img ::

copy:
	mkdir -p /tmp/floppy
	mount -o loop myos.img /tmp/floppy -o fat=12
	sleep 1
	cp haribote.bin /tmp/floppy
	sleep 1
	umount /tmp/floppy
	
$(IMAGE): $(BINFILE)  empty.img os.sys
	dd if=$(BINFILE)  of=$@
	dd if=empty.img of=$@ bs=512 skip=1 seek=1
	dd if=os.sys of=$(IMAGE) bs=1 skip=0 seek=16896 
	dd if=/dev/zero of=$(IMAGE) bs=1 seek=16905 count=1457655

empty.img:
	dd if=/dev/zero of=$@ bs=512 count=2880
	mkdosfs $@

# 0x4200 = 16896
# 9bytes in os.sys 16905

os: os.sys

os.sys: os.nas
	nasm $< -o $@

asm :
	$(MAKE) $(BINFILE) 

run :	#only this option works
#	qemu-system-i386 helloos.img
#	boot from hard disk, it will show Load Error
#	qemu-system-i386 $(IMAGE)
#   boot from floppy, it will not show anything, it's a success!		
	qemu-system-i386 -fda $(IMAGE)	

test: # not working
	qemu-system-i386 -fda ipl.img

#	qemu-system-i386  -drive file=helloos.img,if=floppy	
#	qemu-system-x86_64 -m 32 -fda helloos.img
#	qemu-system-x86_64 -fda helloos.img

install :
	$(MAKE) img
	$(IMGTOL) w a: helloos.img

clean :
	-$(RM) *.img *.bin *.sys

src_only :
	$(MAKE) clean
	-$(RM) helloos.img
